version: '3'
services:
  demo_authorization_server:
    container_name: demo_authorization_server
    image: jboss/keycloak-postgres:3.3.0.CR2
    env_file:
      - ./docker-compose.env
    links:
      - "demo_authorization_server_db:postgres"
    ports:
      - "19010:8080"
    #### To EXPORT/IMPORT, please, check official documentation
    ##
    ## EXPORT REALM ##
    #command: -Dkeycloak.migration.action=export -Dkeycloak.migration.partnerapi=singleFile -Dkeycloak.migration.strategy=OVERWRITE_EXISTING -Dkeycloak.migration.realmName=REAM_NAME_HERE

    ## IMPORT REALM ##
    #command: -Dkeycloak.migration.action=import -Dkeycloak.migration.partnerapi=singleFile -Dkeycloak.migration.strategy=OVERWRITE_EXISTING -Dkeycloak.migration.realmName=REAM_NAME_HERE
    #volumes:
      # Persisted migration export to export using command above
    #  - ./data/keycloak/migration/export:/tmp/keycloak-export
      # Persisted tmp volume
    #  - ./data/keycloak/tmp/persisted:/tmp/persisted
      # To develop themes inline, uncomment following 2 lines below to have a copy of the theme and avoid the use of cache
      #- ./themes/new_theme:/opt/jboss/keycloak/themes/new_theme
    #  - ./keycloak-server.json:/opt/jboss/keycloak/standalone/configuration/keycloak-server.json


  demo_authorization_server_db:
    container_name: demo_authorization_server_db
    image: postgres:9.3
    env_file:
      - ./docker-compose.env
    ports:
      - "19011:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

