version: '2'
services:
  demo_kong:
    container_name: demo_kong
    image: kong:0.11.0
    links:
      - "demo_kong_db"
    env_file:
      - ./docker-compose.env
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  demo_kong_db:
    container_name: demo_kong_db
    image: postgres:9.4
    env_file:
      - ./docker-compose.env
    ports:
      - "5432:5432"

  demo_kong_db_migrations:
    container_name: demo_kong_db_migrations
    image: kong:0.11.0
    links:
      - "demo_kong_db:kong-database"
    env_file:
      - ./docker-compose.env
    command: [ "/bin/sh", "-c", "kong migrations up" ]

